version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: sapunoa-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sapunoa
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: sapunoa-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sapunoa-app
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/sapunoa"
      REDIS_URL: "redis://redis:6379"
      NEXTAUTH_URL: "http://localhost:3007"
      NEXTAUTH_SECRET: "development-secret-change-in-production"
      PORT: "3007"
    ports:
      - "3007:3007"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./.env:/app/.env
    command: >
      sh -c "
        npx prisma migrate deploy &&
        npx prisma db seed &&
        node server.js
      "

volumes:
  postgres-data:
  redis-data: